### ISSUE TITLE
Deleting remote branches

### ISSUE THREAD

**Issue by YOUR1** [matteosister/GitElephant#115]
How can I delete remote branches?

Doing a:
`$gitE->deleteBranch('origin/BRANCH');`
`$gitE->commit('Delete remote branch');`
`$gitE->push();`

doesn't seem to do the trick.

**Comment by BernhardWebstudio** [comment]
An unchecked suggestion: `$repo->push($to, $ref, '-d')` could work.

**Comment by YOUR1** [comment]
Have tried multiple ways, but still a no go. Is there some way to execute a`git push origin :<branch>`?

**Comment by YOUR1** [comment]
Okay, never late then never, but I did it by executing getCall()->execute manually. 
```php
$gitRepository->getCaller()->execute("push origin :{$branchName}");```
