### ISSUE TITLE
Is not valid git repository path

### ISSUE THREAD

**Issue by sarathbabuSwamynathan** [matteosister/GitElephant#116]
Hi, 
I want to manage my git repository which has ssh and http like follows,
ssh = git@localhost:xxxxx/yyyyy.git
http = http://git.zzzz.com:[port number]/xxxxx/yyyyy.git

My code:
----------
$repo = new Repository('git@localhost:xxxxx/yyyyy.git');
$connection = ssh_connect('host', 'myPortNumber');
// authorize the connection with the method you want
ssh2_auth_password($connection, 'myUsername','myPassword');
$caller = new CallerSSH2($connection, 'git@localhost:xxxxx/yyyyy.git');
$repo = Repository::open('git@localhost:xxxxx/yyyyy.git');
$repo->setCaller($caller);
$result = $repo->getStatusOutput();
print_r($result);exit;

When I am executing this code , I am getting following error.

The path provided (git@localhost:xxxxx/yyyyy.git) is not a valid git repository path

Can you please anyone tell me the solution?

**Comment by matteosister** [comment]
this library works with a repository cloned on the filesystem, not with remotes. You have to clone locally. Have a look at the [readme](https://github.com/matteosister/GitElephant)

**Comment by sarathbabuSwamynathan** [comment]
Thanks matteosister.

**Comment by sarathbabuSwamynathan** [comment]
Hi, 
while I am executing with my directory in local file system, I got following error,
Exit code: 127 while executing: \" '-c' 'color.status'='false' status\" with reason: sh: -c: command not found

**Comment by BernhardWebstudio** [comment]
@sarathbabuSwamynathan this looks as if you did not specify the correct path to your git executable. Please open a separate issue in case this separate problem is not resolved by now.
