### ISSUE TITLE
How to push/pull ?

### ISSUE THREAD

**Issue by oDestroyeRo** [matteosister/GitElephant#120]
How to push/pull ?

**Comment by BernhardWebstudio** [comment]
Simply call the functions `push()`respectively `pull()` on your repository object. Check the [source](https://github.com/matteosister/GitElephant/blob/83ff38d0fd9af6a4df13e5edc19758e3510fefe9/src/GitElephant/Repository.php#L1032) for the arguments.

**Comment by matteosister** [comment]
thanks @BernhardWebstudio
