### ISSUE TITLE
live example website is down ?

### ISSUE THREAD

**Issue by Nolwennig** [matteosister/GitElephant#145]
http://gitelephant.cypresslab.net/ doesn't respond ...

**Comment by BernhardWebstudio** [comment]
That is one for you, @matteosister – do you still keep that website active or should it be removed from the README?

**Comment by matteosister** [comment]
it should be removed. I don't have it online anymore. Right now I'm on
holidays so I can't commit. I will do it when I'll be back. Thanks! :)

Il Gio 23 Ago 2018, 15:36 Bernhard Webstudio <notifications@github.com> ha
scritto:

**Comment by Nolwennig** [comment]
https://github.com/matteosister/GitElephant/pull/146 is on way
