### ISSUE TITLE
Problems with Stash and Pop

### ISSUE THREAD

**Issue by AndreFabris** [matteosister/GitElephant#153]
There are no instructions how to use Stash and Pop. This all works as far as I can tell
$repo = Repository::open($installpath . $folder);
$repo->addGlobalConfig('user.email', 'abcd@abcd.com');
$repo->addGlobalConfig('user.name', 'John');
$repo->stashCreate();
$repo->stash('');
$repo->pull($git);

However now I want to pop the stashed changes. I need to pass the string $stash which I have no idea how to get. Whatever string I try to define or get from stashCreate I get something like:
stash pop 'stash@{install}'" with reason: stash@{install} is not a valid reference

Any ideas how to perform stash pop?

**Comment by BernhardWebstudio** [comment]
You can call the `stashPop()` method on the `$repo`. See [code](https://github.com/matteosister/GitElephant/blob/8353f84be962720845e1378d73ed9d4d9ec33a9b/src/GitElephant/Repository.php#L1370) for arguments.

**Comment by AndreFabris** [comment]
Yeah I know, I tried. The argument is string $stash which I have no idea what to pass. Tried a few things none worked.

**Comment by BernhardWebstudio** [comment]
I do not know what you tried, but as far as I know you need to pass the name of the stash which you can get e.g. from `$repo->stashList()`

**Comment by AndreFabris** [comment]
Ok cheers, I will try to see can I get that name from the stashList()

**Comment by BernhardWebstudio** [comment]
Were you able to achive your objective? If so, is it ok if I close this issue? Also, I would love to accept a PR if you want to improve the documentation.

**Comment by Imunhatep** [comment]
No follow up received from the ticket author, I'm closing this.
