### ISSUE TITLE
Update composer.json to allow sf5 versions of dependencies

### ISSUE THREAD

**Issue by gertvdb** [matteosister/GitElephant#162]
If possible also allow sf5 version of the dependencies.   

"symfony/process": "~2.8|~3.0|~4.0|~5.0",
"symfony/filesystem": "~2.8|~3.0|~4.0|~5.0",
"symfony/finder": "~2.8|~3.0|~4.0|~5.0",

**Comment by GenieTim** [comment]
Working on it on branch [`symfony-5-upgrade`](https://github.com/matteosister/GitElephant/tree/symfony-5-upgrade). Feel free to open a PR in any case.
