### ISSUE TITLE
Replace Repo::getTree() with a contrib Tree implementation

### ISSUE THREAD

**Issue by drupol** [matteosister/GitElephant#171]
Hi,

Yesterday while doing #169 I noticed that you have an implementation of a tree structure for Git, which make totally sense.

I was wondering if you would be interested to look at this [package](https://github.com/loophp/phptree).
It's a full blown tree data structure, fast, maintained and tested.

You could get rid of the current tree implementation from this package and delegate it to PHPTree.

What do you think?

**Comment by GenieTim** [comment]
Hi and thanks for reaching out!

I see both pros and cons to this:

Cons:
- breaking change (fix: major version)
- one full-blown dependency more
- separate discussion possible which package to use
- much work to do (possibility e.g. "[adabt](https://en.wikipedia.org/wiki/Adapter_pattern)" the package implementing [TreeishInterface](https://github.com/matteosister/GitElephant/blob/develop/src/GitElephant/Objects/TreeishInterface.php))
- "if it ain't broke, don't fix it"

Pros:
+ one thing less to maintain & test here
+ a separate implementation might be better known/more familiar to users
+ reminder to refactor methods allowing too many input types ([example](https://github.com/matteosister/GitElephant/blob/af03e8530314bebc97f78ec7b2395f3dcd05c624/src/GitElephant/Repository.php#L973))

I see it as a valid option for a next major version of this library (if @Imunhatep does not have major concerns), but not something I would spend time on changing myself.
