### ISSUE TITLE
Driver support

### ISSUE THREAD

**Issue by hason** [matteosister/GitElephant#24]
Implement a system of driver for being able to switch between git calls and libgit2. Add the ability to run commands on a remote machine through ssh connection (php_ssh2 or http://phpseclib.sourceforge.net/).

**Comment by andre-paulo98** [comment]
You don't need to buy a Windows license to try it @matteosister.
The .iso image for Windows 10 is publicly available on Microsoft Website.
The only thing you'll get is a annoying watermark on the bottom of the screen saying to activate Windows.
https://www.microsoft.com/en-gb/software-download/windows10
