### ISSUE TITLE
$repo->GetTags is WAY too slow.     Support for "git for-each-ref" is needed (solution code included)

### ISSUE THREAD

**Issue by John-Schlick** [matteosister/GitElephant#52]
$repository->getTags is VERY slow on repositories that have hundereds of tags.  This is becasue each tag requires another system process to make the call to get it's sha.

If you do not need ALL the tags, it is much faster to use for-each-ref and have it get ALL the information that you need to create the tag without an additional exec. (In fact, I suspect this would be a better implementation for getTags in general due to speed.)

I have implemented $repository->getRecentTags($count)

Honestly, this implementation seems like it's just a hair out of line with what you normally do...  You seem to have the parse (in the command) create the resultant object, I feel far more comfortable having the repository object directly do the create from the output of the parse, but it would be really easy to have the parse create and return a tag and then just add that to the $tagArray in the repository object if thats your preference.

Again, I'd do a pull request, but your unit tests don't run without more configuration than I have time for. They fail to start, with complaints about files not existing, and you insist that pull requests must have unit tests.  Oh well.

So, instead, I'm including the code diff that makes this fix go, and go a LOT faster: (If you'd rather have a pull request, I'm happy to generate one, if you want me to email the files, I'm happy to do that.  If you want just the code snippets, I'm also happy to give you that.)

jschlick@dvm-jschlick1:/usr/local/development-process-master/common/lib/GitElephant/vendor/cypresslab/gitelephant(BGS-1269)$ git diff origin/BGS-1269
diff --git a/common/lib/GitElephant/vendor/cypresslab/gitelephant/src/GitElephant/Command/ForEachRefCommand.php b/common/lib/GitElephant/vend
new file mode 100755
index 0000000..1243d52
--- /dev/null
+++ b/common/lib/GitElephant/vendor/cypresslab/gitelephant/src/GitElephant/Command/ForEachRefCommand.php
@@ -0,0 +1,135 @@
+<?php
+/**
- \* GitElephant - An abstraction layer for git written in PHP
- \* Copyright (C) 2014  John Schlick
- *
- \* This program is free software: you can redistribute it and/or modify
- \* it under the terms of the GNU General Public License as published by
- \* the Free Software Foundation, either version 3 of the License, or
- \* (at your option) any later version.
- *
- \* This program is distributed in the hope that it will be useful,
- \* but WITHOUT ANY WARRANTY; without even the implied warranty of
- \* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
- \* GNU General Public License for more details.
- *
- \* You should have received a copy of the GNU General Public License
- \* along with this program.  If not, see [http://www.gnu.org/licenses/].
- _/
  +
  +namespace GitElephant\Command;
  +
  +use GitElephant\Objects\Tag;
  +use GitElephant\Objects\Commit;
  +use GitElephant\Exception\InvalidArgumentException;
  +
  +/_*
- \* ForEachRef Command generator
- *
- \* @author John Schlick john_schlick@hotmail.com
- */
  +class ForEachRefCommand extends BaseCommand
  +{
-    const GIT_FOR_EACH_REF = 'for-each-ref';
  +
-    // The types of objects to take a look at.
-    const TYPE_TAGS = 'refs/tags';
  +
-    const OPTION_SORT = '--sort=';
-    const OPTION_FORMAT = '--format=';
-    const OPTION_COUNT = '--count=';
  +
-    // If there is no message, use this one.
-    const OPTION_SORT_COMMITTERDATE = '-committerdate';
-    // As long as there is always a message with the tag, then use this one.
-    const OPTION_SORT_TAGGERDATE = '-taggerdate';
  +
-    // The ones with stars reach into the commit for their information.
-    const OPTION_FORMAT_OBJECTNAME = '%(*objectname)';
-    const OPTION_FORMAT_OBJECTTYPE = '%(objecttype)';
-    const OPTION_FORMAT_REFNAME = '%(refname)';
-    const OPTION_FORMAT_AUTHORDATE = '%(*authordate)';
-    const OPTION_FORMAT_SUBJECT = '%(*subject)';
  +
-    // Constants for names for array indexed when we parse.
-    const COMPONENT_SHA = 'SHA'; // The objectname above.
-    const COMPONENT_TYPE = 'TYPE'; // The objecttype above.
-    const COMPONENT_NAME = 'NAME'; // the refname above.
-    const COMPONENT_DATE = 'DATE'; // The authordate above.
-    const COMPONENT_COMMENT = 'COMMENT'; // the subject above.
  +
-    /**
-     \* @return RevListCommand
-     */
-    public static function getInstance()
-    {
-        return new self();
-    }
  +
-    /**
-     \* get output lines that make sense for the last n tags.
-     *
-     \* @param \GitElephant\Objects\Tag $tag a tag instance
-     *
-     \* @throws \RuntimeException
-     \* @return string
-     */
-    public function getRecentTags($count)
-    {
-        $this->clearAll();
  +
-        $this->addCommandName(static::GIT_FOR_EACH_REF);
  +
-        $this->addCommandSubject(static::TYPE_TAGS);
  +
-        // specify it's sort order.
-        $this->addCommandArgument(static::OPTION_SORT . static::OPTION_SORT_TAGGERDATE);
  +
-        // Specify the format of output we want.
-        $format = static::OPTION_FORMAT . '"' .
-            static::OPTION_FORMAT_OBJECTNAME .
-            "#" .
-            static::OPTION_FORMAT_OBJECTTYPE .
-            "#" .
-            static::OPTION_FORMAT_REFNAME .
-            "#" .
-            static::OPTION_FORMAT_AUTHORDATE .
-            "#" .
-            static::OPTION_FORMAT_SUBJECT .
-            '"';
-        $this->addCommandArgument($format);
  +
-        // Now add how many to get.
-        $this->addCommandArgument(static::OPTION_COUNT . $count);
  +
-        return $this->getCommand();
-    }
  +
-    /**
-     \* take a recent tag output line and break it into component parts.
-     *
-     \* @param string $tagString - the string to parse.
-     *
-     \* @throws \RuntimeException
-     \* @return array indexed by COMPONENT_xxx constants.
-     */
-    public function parseRecentTagString($tagString)
-    {
-        $tagString = trim($tagString, '"');
-        $tagComponents = explode('#', $tagString, 5);
-        if (!is_array($tagComponents) || count($tagComponents) !== 5) {
-            throw new InvalidArgumentException($repositoryPath);
-        }
  +
-        // Make the array we will return.
-        $namedTagComponents = array();
-        $namedTagComponents[static::COMPONENT_SHA] = $tagComponents[0];
-        $namedTagComponents[static::COMPONENT_TYPE] = $tagComponents[1];
-        $namedTagComponents[static::COMPONENT_NAME] = $tagComponents[2];
-        // Strip the refs/tags off the name so that we can JUST have the tagname.
-        $prefix = 'refs/tags/';
-        if (substr($namedTagComponents[static::COMPONENT_NAME], 0, strlen($prefix)) === $prefix) {
-            $namedTagComponents[static::COMPONENT_NAME] = substr($namedTagComponents[static::COMPONENT_NAME], strlen($prefix));
-        }
-        $namedTagComponents[static::COMPONENT_DATE] = $tagComponents[3];
-        $namedTagComponents[static::COMPONENT_COMMENT] = $tagComponents[4];
  +
-        return $namedTagComponents;
-    }
  +}
  diff --git a/common/lib/GitElephant/vendor/cypresslab/gitelephant/src/GitElephant/Objects/Tag.php b/common/lib/GitElephant/vendor/cypresslab/
  old mode 100644
  new mode 100755
  index e6a6018..681b142
  --- a/common/lib/GitElephant/vendor/cypresslab/gitelephant/src/GitElephant/Objects/Tag.php
  +++ b/common/lib/GitElephant/vendor/cypresslab/gitelephant/src/GitElephant/Objects/Tag.php
  @@ -52,6 +52,20 @@ class Tag extends Object
   private $sha;
  
   /**
-     \* comment
-     *
-     \* @var string
-     */
-    private $comment;
  +
-    /**
-     \* authorDate
-     *
-     \* @var string
-     */
-    private $authorDate;
  +
-    /**
  - Creates a new tag on the repository and returns it
    *
  - @param \GitElephant\Repository $repository repository instance
    @@ -99,12 +113,19 @@ class Tag extends Object
  - @throws \InvalidArgumentException
  - @internal param string $line a single tag line from the git binary
    */
-    public function __construct(Repository $repository, $name)
-    public function __construct(Repository $repository, $name, $sha = null, $authorDate=null, $comment = null)
   {
       $this->repository = $repository;
       $this->name    = $name;
       $this->fullRef = 'refs/tags/' . $this->name;
-        $this->createFromCommand();
-        if (is_null($sha)) {
-            $this->createFromCommand();
-        } else {
-            $this->setSha($sha);
-        }
  +
-        $this->comment = $comment;
- ```
     $this->authorDate = $authorDate;
  ```
  
   }
  
   /**
  @@ -251,4 +272,24 @@ class Tag extends Object
   {
       return $this->sha;
   }
  +
-    /**
-     \* comment getter
-     *
-     \* @return string
-     */
-    public function getComment()
-    {
-        return $this->comment;
-    }
  +
-    /**
-     \* authorDate getter
-     *
-     \* @return string
-     */
-    public function getAuthorDate()
-    {
-        return $this->authorDate;
-    }
  }
  diff --git a/common/lib/GitElephant/vendor/cypresslab/gitelephant/src/GitElephant/Repository.php b/common/lib/GitElephant/vendor/cypresslab/g
  index 96a473d..659c612 100755
  --- a/common/lib/GitElephant/vendor/cypresslab/gitelephant/src/GitElephant/Repository.php
  +++ b/common/lib/GitElephant/vendor/cypresslab/gitelephant/src/GitElephant/Repository.php
  @@ -40,6 +40,7 @@ use GitElephant\Command\MainCommand;
  use GitElephant\Command\BranchCommand;
  use GitElephant\Command\MergeCommand;
  use GitElephant\Command\ResetCommand;
  +use GitElephant\Command\ForEachRefCommand;
  use GitElephant\Command\RevParseCommand;
  use GitElephant\Command\TagCommand;
  use GitElephant\Command\LogCommand;
  @@ -632,6 +633,31 @@ class Repository
   }
  
   /**
-     \* Gets an array of Tag objects
-     *
-     \* @param string $count count of the most recent tags to get.
-     *
-     \* @throws \RuntimeException
-     \* @throws \Symfony\Component\Process\Exception\LogicException
-     \* @throws \Symfony\Component\Process\Exception\InvalidArgumentException
-     \* @throws \Symfony\Component\Process\Exception\RuntimeException
-     \* @return array
-     */
-    public function getRecentTags($count)
-    {
-        $tags = array();
-        $this->caller->execute(ForEachRefCommand::getInstance()->getRecentTags($count));
-        foreach ($this->caller->getOutputLines() as $tagString) {
-            if ($tagString != '') {
-                $tagComponents = ForEachRefCommand::getInstance()->parseRecentTagString($tagString);
-                $tags[] = new Tag($this, $tagComponents[ForEachRefCommand::COMPONENT_NAME], $tagComponents[ForEachRefCommand::COMPONENT_SHA]
-            }
-        }
  +
-        return $tags;
-    }
  +
-    /**
  - Return a tag object
    *
  - @param string $name The tag name
    jschlick@dvm-jschlick1:/usr/local/development-process-master/common/lib/GitElephant/vendor/cypresslab/gitelephant(BGS-1269)$

**Comment by ntd** [comment]
No need to incomodate `git-for-each-ref`: you can still use `git-tag` to get tag name and hash in a single shot:

    git tag --format='%(refname:strip=2)%09%(objectname)'

**Comment by BernhardWebstudio** [comment]
Feel free to open a PR, thanks in advance!
