### ISSUE TITLE
git elephant gush integration

### ISSUE THREAD

**Issue by cordoval** [matteosister/GitElephant#53]
sometimes i think that having an abstraction in gush could be used standalone

i mean gush uses adapters to do macro hub operations, like hub

i think it is possible perhaps to create an adapter for gitelephant, so a gush-gitelephant-adapter in such a way that the adapter and issue tracker interface implementations looks like it is interacting with github but it is stored or hold in our servers or locally

this would be of great interest to gain a good abstraction between gush and gitelephant for the profit of projects

cc/ @sstok

**Comment by BernhardWebstudio** [comment]
@cordoval; me, as a contributor with the objective to reduce the number of open issues, I wonder if this is still an ongoing situation? Did you find a solution, 4 years ago?
