### ISSUE TITLE
Is possible to get history of one file ?

### ISSUE THREAD

**Issue by difuse** [matteosister/GitElephant#80]
Hi !

I can't find how to get the history of a single file with GitElephant.
I want be able to get all the history of a file and his diff from a path.

If a good soul could give me a little help :)

Thanks a lot.

**Comment by matteosister** [comment]
Hi! You are looking for the **getLog** function. 

Here is a simple snippet that, given a path or file, returns the history

``` php
$repo = new \GitElephant\Repository('/path/to/repo');
// the first argument is the branch
// the second argument is the subject path you want the history of
// 100 is the number of entries. It is limited to 10 by default
$log = $repo->getLog('HEAD', 'file or path', 100);
/** @var \GitElephant\Objects\Commit $commit */
foreach ($log as $commit) {
    echo $commit->getSha(true) .': '.$commit->getMessage()."\n";
}
```

**Comment by difuse** [comment]
Thank you @matteosister !

I still have a problem because when I call $commit->get_diff(), I've all the diff but i want to get history and diff on one single file.

Like
```
git log --all-match --follow -p Article\ 34.md
```
I get just the history of "Article 34.md".

Actually, i have this code :

```php
$log = $repo->getLog('HEAD', $article->path.'/'.$article->file, 100);

foreach ($log as $commit) {
  $commits[] = array(
	'sha' => $commit->getSha(true),
	'message' => $commit->getMessage(),
	'diff' => $commit->getDiff(),
  );
}
print_r($commits);

```

But the problem is this code return me all the diff of the commit.
Do you have an idea ?

Thanks !
Robin

**Comment by matteosister** [comment]
@difuse there is no such thing is git...I mean a commit is a full and "meaningful" change to the code, and it's not a good idea to show only a part of the commit diff imho.

But you can do something with the Diff object. As you can see [here](https://github.com/matteosister/GitElephant#diffs) you can iterate over a **Diff** instance and get a list of [DiffObject](https://github.com/matteosister/GitElephant/blob/develop/src/GitElephant/Objects/Diff/DiffObject.php) instance. Here you have the original file name and the destination file name...so you can filter these objects to show only the diff you need...just an idea...
