### ISSUE TITLE
Hard time understanding how to use the SSH2 Remote implementation

### ISSUE THREAD

**Issue by Brainshack** [matteosister/GitElephant#81]
Hello,

I am currently trying to fetch information of a repository on a remote server via ssh. However, there seem to be some issues, I can't get my head wrapped arround.

1. When creating an instance of `Repository`, the constructor will always check, if the provided repository exists on the machine, the script is executed on
    
   `if (!is_dir($repositoryPath)) {`
    `    throw new InvalidRepositoryPathException($repositoryPath);`
    `}`

This does not make sense, since you want to query information from a different machine. I believe this check should be moved to the `Caller`class instead.

2. When executing a command like `log`, the path of the repository seems to be not considered.

`$repo->getTree()`, for example, will result in the follwing command being executed on the remote machine via ssh `git ls-tree '-l' 'HEAD'`. The path of the repository is not being used here at all, which will cause everything to lead to empty results.

Here is the full code I am working with:

`        $connection = \ssh2_connect('remote.host', 22, array('hostkey'=>'ssh-rsa'));`

`        // authorize the connection with the method you want`
`        \ssh2_auth_pubkey_file(`
`            $connection,`
`            'user',`
`            realpath(__DIR__ . '/../Resources/ssh/id_rsa.pub'),`
`            realpath(__DIR__ . '/../Resources/ssh/id_rsa'),`
`            ''`
`        );`

`        $caller = new CallerSSH2($connection, 'git');`
`        $repo = Repository::open('path/to/repository/on/remote/server');`
`        $repo->setCaller($caller);`
`        dump($repo->getTree());`

Am I maybe just doing it wrong?

**Comment by matteosister** [comment]
Thanks for the head up!
there are definitely some problem with the remote implementation....
It deserves some love but I really don't have time right now. Do you? :smile:

**Comment by Brainshack** [comment]
Since I need this feature, I will definitly have a look. Just wanted to make sure that I am not doing it wrong :)

**Comment by matteosister** [comment]
it's the library that have a problem with this...never needed this feature for myself, so I never spent so much time with it...if you want to create a pr and share your code it would be great!
