### ISSUE TITLE
[Q] About SSH Agent

### ISSUE THREAD

**Issue by LeoBenoist** [matteosister/GitElephant#86]
Hello @matteosister,

I am running into a problem that will probably have an obvious solution.

What I am trying to achieve: Cloning locally a private repository protected by a ssh auth.
The problem: "Permission denied, please try again.", the key pair is not working.
Consideration: Apache/PHP user have access to that key-pair and the crashing command work in a terminal.
Reason: In https://github.com/matteosister/GitElephant/blob/v1.0.14/src/GitElephant/Command/Caller/Caller.php#L109 the clone command is executed using symfony process component. It appear that the Process does not have access to the ssh agent.

Indeed if I replace (for testing purpose)

        $process = new Process($cmd, is_null($cwd) ? $this->repositoryPath : $cwd);

with (starting the ssh-agent):

       $process = new Process('exec ssh-agent bash && ' .$cmd, is_null($cwd) ? $this->repositoryPath : $cwd);

My question:
How do you transmit your agent to the library ?

Thanks :)

**Comment by matteosister** [comment]
I don't think it's possible, with the current implementation, to handle this problem. Maybe there is an option in the process component that enable the environment. But there isn't a method to customize how the command gets executed.

Do you really need to clone from GitElephant? Maybe you could use a script for that and then interact with the repo.

Maybe this could be done by implementing a process builder in the GitElephant\Command\Caller class, and by letting this to be customized.

**Comment by LeoBenoist** [comment]
It is what I did for now. Cloning outside GitElephant. I was just wondering if you ran into that and find a workaround. Thanks for your quick answer :)

**Comment by LeoBenoist** [comment]
Hello @matteosister 
If you need the it or someone need it one day this is my solution. My requirement was the possibility to add a custom key pair on each command.

The new Caller

```php
<?php

namespace Caller;

use GitElephant\Command\Caller\Caller as BaseCaller;
use GitElephant\GitBinary;

/**
 * @author Léo Benoist
 */
class Caller extends BaseCaller
{
    /**
     * @var GitBinary
     */
    protected $binary;

    /**
     * @var string
     */
    protected $privateKeyPath;

    /**
     * {@inheritdoc}
     */
    public function __construct(GitBinary $binary, $repositoryPath)
    {
        parent::__construct($binary, $repositoryPath);
        $this->binary = $binary;
        $this->binary->setPath($this->getGitAuthenticationCommand().' '.$this->binary->getPath());
    }

    /**
     * @param string $privateKeyPath
     *
     * @return Caller
     */
    public function setPrivateKeyPath($privateKeyPath)
    {
        exec('chmod 600 '.$privateKeyPath);
        exec('chmod 644 '.$privateKeyPath.'.pub');
        $gitKeyConfig = '#!/bin/sh
            ssh -i '.$privateKeyPath.' -F /dev/null -p 22 $*
        ';

        file_put_contents('/tmp/papo_git_key.sh', $gitKeyConfig);
        exec('chmod 755 /tmp/papo_git_key.sh');
    }

    /**
     * @return string
     */
    protected function getGitAuthenticationCommand()
    {
        return 'GIT_SSH=/tmp/private_git_key.sh';
    }
}
```

And the new repository object:

```php
<?php

namespace Akeneo\Bundle\DistributionBundle\Model;

use \Caller;
use GitElephant\GitBinary;
use GitElephant\Objects\Commit;
use GitElephant\Repository as BaseRepository;

/**
 * @author Léo Benoist
 */
class Repository extends BaseRepository
{
    /**
     * @var string
     */
    protected $privateKeyPath;

    /**
     * {@inheritdoc}
     */
    public function __construct($repositoryPath, GitBinary $binary = null, $name = null)
    {
        if (is_null($binary)) {
            $binary = new GitBinary();
        }

        parent::__construct($repositoryPath, $binary, $name);
        $this->setCaller(new Caller($binary, $repositoryPath));
    }

    /**
     * @param string $privateKeyPath
     *
     * @return Repository
     */
    public function setPrivateKeyPath($privateKeyPath)
    {
        $this->getCaller()->setPrivateKeyPath($privateKeyPath);

        return $this;
    }
}
```

**Comment by matteosister** [comment]
thanks for sharing
