### ISSUE TITLE
Show file contents at a particular commit

### ISSUE THREAD

**Issue by kachkaev** [matteosister/GitElephant#88]
Here is what I'm trying to execute:
```
git show commit_ref:path_to_file.txt
```
It seems like there is no way of doing this with GetElephant at the moment. ShowCommand exists, but it is only applicable to a commit. Are you planning to implement something like ```$object->show()``` for blobs? Any temporal workaround?

My ultimate goal is to dump the state of the whole repository at a particular commit into another directory without making changes in a working copy. Maybe that can be done somehow else.

Cheers!

**Comment by matteosister** [comment]
look if you can do something with these two methods: https://github.com/matteosister/GitElephant/blob/develop/src/GitElephant/Repository.php#L1054-L1090 and the relative [cat-file git command](https://github.com/matteosister/GitElephant/blob/develop/src/GitElephant/Command/CatFileCommand.php)

**Comment by kachkaev** [comment]
Thanks @matteosister! Sorry, I still can't figure out what exactly to call. Let's say I'm trying to output the contents of ```path/to/file.txt``` from ```$repository``` at ```0h2s8723....```. Could you please suggest what to write? Others may find this info helpful too.

Cheers!

**Comment by matteosister** [comment]
you're right. I just pushed [an example file](https://github.com/matteosister/GitElephant/blob/develop/examples/show_file_contents.php), let me know if it's clear enogh!

**Comment by matteosister** [comment]
and remember, you could also use outputContent to get an array of lines, instead of a string. Useful for templating in some cases.

**Comment by kachkaev** [comment]
Thank you!
