### ISSUE TITLE
Clone on windows

### ISSUE THREAD

**Issue by DONGChuan** [matteosister/GitElephant#91]
Hi,

I tried it to clone a project on windows, it needs to change:

const GIT_CLONE_COMMAND = 'clone';

to

const GIT_CLONE_COMMAND = 'git clone';

I think, maybe other GIT_XX_COMMAND need to be done the same thing on windows

**Comment by matteosister** [comment]
The GitBinary need to know where is your git binary. Have a look here: https://github.com/matteosister/GitElephant/blob/develop/src/GitElephant/GitBinary.php#L42-L49

So when you create the GitBinary object just pass it to the constructor.
I'm not aware of a reliable way to find a binary in windows....

**Comment by DONGChuan** [comment]
@matteosister Thank you for infos. Why not add it on the readme. It could be easier for the freshman like me to know where the problem is :P

By the way, if you have time to reply my stupid question. Why we do it like this? Because if we install git on our systems(windows/linux and so on). And git is usually and should be added in the class path, we only need to call:

const GIT_CLONE_COMMAND = 'git clone';

**Comment by DONGChuan** [comment]
@matteosister What's more, on windows, the normal way to configure GitBinary will not work.

new GitBinary('path/to/git'); here, I tried path/bin, path/bin/git, path/bin/git.exe. None of them work.

So the solution now is to keep Git in classpath then:

$this->gitBinary = new GitBinary('git');
$this->workSpace = new Repository('path/to/repo', $this->gitBinary);

**Comment by matteosister** [comment]
the last solution seems ok...if you find the "proper" way to do it I'll add it to the readme.

Thanks!
